import { useState } from 'react';
import Head from 'next/head';

export default function Home() {
  const [activeTab, setActiveTab] = useState('design');
  const [generatedPrompt, setGeneratedPrompt] = useState('');
  const [arabicContent, setArabicContent] = useState('');
  const [showArabic, setShowArabic] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState(null);
  const [uploadedImage, setUploadedImage] = useState(null);
  const [uploadedImageName, setUploadedImageName] = useState('');
  const [inputMode, setInputMode] = useState('description');
  const [designStyle, setDesignStyle] = useState('elegant');
  const [designCategory, setDesignCategory] = useState('dress');
  const [designColor, setDesignColor] = useState('black');
  const [designFabric, setDesignFabric] = useState('silk');
  const [designSeason, setDesignSeason] = useState('spring-summer');
  const [designOccasion, setDesignOccasion] = useState('evening');
  const [designDetails, setDesignDetails] = useState('');
  const [videoType, setVideoType] = useState('runway');
  const [videoMood, setVideoMood] = useState('dramatic');
  const [videoCamera, setVideoCamera] = useState('slow-pan');
  const [videoLighting, setVideoLighting] = useState('studio');
  const [videoDuration, setVideoDuration] = useState('15');
  const [videoDetails, setVideoDetails] = useState('');
  const [marketingPlatform, setMarketingPlatform] = useState('instagram-reel');
  const [marketingTone, setMarketingTone] = useState('luxury');
  const [productName, setProductName] = useState('');
  const [productDesc, setProductDesc] = useState('');
  const [includeHashtags, setIncludeHashtags] = useState(true);
  const [includeEmojis, setIncludeEmojis] = useState(true);
  const [marketingCTA, setMarketingCTA] = useState('shop-now');
  const [storyTone, setStoryTone] = useState('luxury');
  const [storyLength, setStoryLength] = useState('medium');
  const [storyDesc, setStoryDesc] = useState('');

  const styles = [{id:'elegant',en:'Elegant',ar:'أنيق'},{id:'casual',en:'Casual',ar:'كاجوال'},{id:'streetwear',en:'Streetwear',ar:'ستريت وير'},{id:'haute-couture',en:'Haute Couture',ar:'هوت كوتور'},{id:'minimalist',en:'Minimalist',ar:'مينيمالست'},{id:'bohemian',en:'Bohemian',ar:'بوهيمي'},{id:'sporty',en:'Sporty',ar:'رياضي'},{id:'vintage',en:'Vintage',ar:'فينتج'},{id:'avant-garde',en:'Avant-Garde',ar:'أفانت غارد'},{id:'romantic',en:'Romantic',ar:'رومانسي'}];
  const categories = [{id:'dress',en:'Dress',ar:'فستان'},{id:'suit',en:'Suit',ar:'بدلة'},{id:'jacket',en:'Jacket',ar:'جاكيت'},{id:'pants',en:'Pants',ar:'بنطلون'},{id:'skirt',en:'Skirt',ar:'تنورة'},{id:'blouse',en:'Blouse',ar:'بلوزة'},{id:'coat',en:'Coat',ar:'معطف'},{id:'abaya',en:'Abaya',ar:'عباية'},{id:'kaftan',en:'Kaftan',ar:'قفطان'},{id:'jumpsuit',en:'Jumpsuit',ar:'جمبسوت'}];
  const colors = [{id:'black',en:'Black',ar:'أسود',hex:'#000000'},{id:'white',en:'White',ar:'أبيض',hex:'#FFFFFF'},{id:'red',en:'Red',ar:'أحمر',hex:'#DC2626'},{id:'navy',en:'Navy Blue',ar:'كحلي',hex:'#1E3A5F'},{id:'emerald',en:'Emerald',ar:'زمردي',hex:'#059669'},{id:'gold',en:'Gold',ar:'ذهبي',hex:'#D4AF37'},{id:'burgundy',en:'Burgundy',ar:'خمري',hex:'#722F37'},{id:'blush',en:'Blush Pink',ar:'وردي فاتح',hex:'#FEC5BB'},{id:'royal-blue',en:'Royal Blue',ar:'أزرق ملكي',hex:'#4169E1'},{id:'champagne',en:'Champagne',ar:'شامبين',hex:'#F7E7CE'}];
  const fabrics = [{id:'silk',en:'Silk',ar:'حرير'},{id:'velvet',en:'Velvet',ar:'مخمل'},{id:'cotton',en:'Cotton',ar:'قطن'},{id:'linen',en:'Linen',ar:'كتان'},{id:'leather',en:'Leather',ar:'جلد'},{id:'satin',en:'Satin',ar:'ساتان'},{id:'chiffon',en:'Chiffon',ar:'شيفون'},{id:'lace',en:'Lace',ar:'دانتيل'},{id:'tweed',en:'Tweed',ar:'تويد'},{id:'organza',en:'Organza',ar:'أورجانزا'}];
  const seasons = [{id:'spring-summer',en:'Spring/Summer',ar:'ربيع/صيف'},{id:'fall-winter',en:'Fall/Winter',ar:'خريف/شتاء'},{id:'resort',en:'Resort',ar:'ريزورت'},{id:'pre-fall',en:'Pre-Fall',ar:'ما قبل الخريف'}];
  const occasions = [{id:'evening',en:'Evening/Gala',ar:'سهرة'},{id:'casual',en:'Casual',ar:'يومي'},{id:'formal',en:'Formal/Business',ar:'رسمي'},{id:'wedding',en:'Wedding',ar:'زفاف'},{id:'party',en:'Party',ar:'حفلة'},{id:'cocktail',en:'Cocktail',ar:'كوكتيل'}];
  const videoTypes = [{id:'runway',en:'Runway Show',ar:'عرض أزياء'},{id:'lookbook',en:'Lookbook',ar:'لوك بوك'},{id:'product',en:'Product Showcase',ar:'عرض منتج'},{id:'behind-scenes',en:'Behind The Scenes',ar:'خلف الكواليس'},{id:'transformation',en:'Transformation',ar:'تحول'},{id:'styling',en:'Styling Tips',ar:'نصائح تنسيق'}];
  const videoMoods = [{id:'dramatic',en:'Dramatic',ar:'درامي'},{id:'elegant',en:'Elegant',ar:'راقي'},{id:'energetic',en:'Energetic',ar:'حيوي'},{id:'romantic',en:'Romantic',ar:'رومانسي'},{id:'mysterious',en:'Mysterious',ar:'غامض'},{id:'minimalist',en:'Minimalist',ar:'بسيط'}];
  const cameraMoves = [{id:'slow-pan',en:'Slow Pan',ar:'تحريك بطيء'},{id:'360-rotation',en:'360° Rotation',ar:'دوران 360°'},{id:'zoom-in',en:'Zoom In',ar:'تقريب'},{id:'tracking',en:'Tracking Shot',ar:'تتبع'},{id:'dolly',en:'Dolly Movement',ar:'دولي'},{id:'crane',en:'Crane Shot',ar:'رافعة'}];
  const lightingTypes = [{id:'studio',en:'Studio Lighting',ar:'إضاءة استديو'},{id:'natural',en:'Natural Light',ar:'إضاءة طبيعية'},{id:'dramatic',en:'Dramatic Shadows',ar:'ظلال درامية'},{id:'golden-hour',en:'Golden Hour',ar:'الساعة الذهبية'},{id:'neon',en:'Neon Lights',ar:'إضاءة نيون'},{id:'soft',en:'Soft Diffused',ar:'إضاءة ناعمة'}];
  const platforms = [{id:'instagram-reel',en:'Instagram Reel',ar:'ريل انستغرام'},{id:'instagram-post',en:'Instagram Post',ar:'بوست انستغرام'},{id:'instagram-story',en:'Instagram Story',ar:'ستوري انستغرام'},{id:'tiktok',en:'TikTok',ar:'تيك توك'},{id:'facebook',en:'Facebook',ar:'فيسبوك'},{id:'pinterest',en:'Pinterest',ar:'بنترست'}];
  const tones = [{id:'luxury',en:'Luxury',ar:'فاخر'},{id:'friendly',en:'Friendly',ar:'ودي'},{id:'professional',en:'Professional',ar:'احترافي'},{id:'playful',en:'Playful',ar:'مرح'},{id:'urgent',en:'Urgent',ar:'عاجل'},{id:'inspiring',en:'Inspiring',ar:'ملهم'}];
  const goals = [{id:'awareness',en:'Brand Awareness',ar:'زيادة الوعي'},{id:'sales',en:'Drive Sales',ar:'زيادة المبيعات'},{id:'engagement',en:'Engagement',ar:'زيادة التفاعل'},{id:'launch',en:'Product Launch',ar:'إطلاق منتج'},{id:'promotion',en:'Promotion/Sale',ar:'عرض/خصم'}];
  const ctas = [{id:'shop-now',en:'Shop Now',ar:'تسوقي الآن'},{id:'learn-more',en:'Learn More',ar:'اعرفي المزيد'},{id:'link-bio',en:'Link in Bio',ar:'الرابط في البايو'},{id:'dm',en:'DM to Order',ar:'راسلينا للطلب'},{id:'limited',en:'Limited Stock',ar:'كمية محدودة'}];
  const storyLengths = [{id:'short',ar:'قصيرة'},{id:'medium',ar:'متوسطة'},{id:'long',ar:'طويلة'}];

  const handleImageUpload = (e) => { const file = e.target.files[0]; if (file) { const reader = new FileReader(); reader.onload = (ev) => { setUploadedImage(ev.target.result); setUploadedImageName(file.name); }; reader.readAsDataURL(file); } };
  const removeUploadedImage = () => { setUploadedImage(null); setUploadedImageName(''); };

  const generateDesignPrompt = () => {
    const style = styles.find(s => s.id === designStyle);
    const category = categories.find(c => c.id === designCategory);
    const color = colors.find(c => c.id === designColor);
    const fabric = fabrics.find(f => f.id === designFabric);
    const season = seasons.find(s => s.id === designSeason);
    const occasion = occasions.find(o => o.id === designOccasion);
    const imgNote = inputMode === 'image' && uploadedImage ? 'Based on the uploaded reference image:\n\n' : '';
    const promptEn = `${imgNote}High-end fashion photography, ${style.en} ${color.en} ${fabric.en} ${category.en}, ${season.en} collection, perfect for ${occasion.en}. Professional runway model, Vogue magazine quality, studio lighting, 8K resolution, masterful tailoring, luxury brand aesthetic.${designDetails ? ` Details: ${designDetails}` : ''}\n\n--ar 3:4 --style raw --v 6.1\n\nNegative: low quality, amateur, wrinkled, blurry`;
    const promptAr = `${inputMode === 'image' && uploadedImage ? 'بناءً على الصورة المرفقة:\n\n' : ''}تصوير أزياء راقي، ${category.ar} ${style.ar} بلون ${color.ar} من قماش ${fabric.ar}، مجموعة ${season.ar}، مثالي لمناسبات ${occasion.ar}. عارضة أزياء محترفة، جودة مجلة فوغ، إضاءة استديو، دقة 8K، خياطة متقنة، جمالية علامة فاخرة.${designDetails ? ` التفاصيل: ${designDetails}` : ''}\n\n--ar 3:4 --style raw --v 6.1\n\nسلبي: جودة منخفضة، هاوي، مجعد، ضبابي`;
    setGeneratedPrompt(promptEn);
    setArabicContent(promptAr);
  };

  const generateVideoPrompt = () => {
    const type = videoTypes.find(t => t.id === videoType);
    const mood = videoMoods.find(m => m.id === videoMood);
    const camera = cameraMoves.find(c => c.id === videoCamera);
    const lighting = lightingTypes.find(l => l.id === videoLighting);
    const imgNote = inputMode === 'image' && uploadedImage ? 'Based on the uploaded reference image:\n\n' : '';
    const promptEn = `${imgNote}Cinematic fashion film, ${type.en} style, ${mood.en} atmosphere.\n\nDURATION: ${videoDuration} seconds\nCAMERA: ${camera.en}\nLIGHTING: ${lighting.en}\n\nProfessional model showcasing haute couture, 4K cinematic, elegant fabric movement.${videoDetails ? ` Notes: ${videoDetails}` : ''}\n\nTECHNICAL: 24fps, 9:16 or 16:9`;
    const promptAr = `${inputMode === 'image' && uploadedImage ? 'بناءً على الصورة المرفقة:\n\n' : ''}فيلم أزياء سينمائي، أسلوب ${type.ar}، أجواء ${mood.ar}.\n\nالمدة: ${videoDuration} ثانية\nالكاميرا: ${camera.ar}\nالإضاءة: ${lighting.ar}\n\nعارضة محترفة تستعرض هوت كوتور، سينمائي 4K، حركة قماش أنيقة.${videoDetails ? ` ملاحظات: ${videoDetails}` : ''}\n\nتقني: 24 إطار/ثانية، 9:16 أو 16:9`;
    setGeneratedPrompt(promptEn);
    setArabicContent(promptAr);
  };

  const generateMarketingPrompt = () => {
    const platform = platforms.find(p => p.id === marketingPlatform);
    const cta = ctas.find(c => c.id === marketingCTA);
    const name = productName || '[Product Name]';
    const nameAr = productName || '[اسم المنتج]';
    const desc = productDesc || 'Luxury fashion piece';
    const descAr = productDesc || 'قطعة أزياء فاخرة';
    let contentEn = inputMode === 'image' && uploadedImage ? '[Based on uploaded product image]\n\n' : '';
    let contentAr = inputMode === 'image' && uploadedImage ? '[بناءً على صورة المنتج المرفقة]\n\n' : '';
    if (marketingPlatform.includes('reel') || marketingPlatform === 'tiktok') {
      contentEn += `📱 ${platform.en} SCRIPT - ${name}\n\n⏱️ DURATION: 15-30 seconds\n\n🎬 SCENE 1 - HOOK (0-3s):\n[Close-up of fabric detail]\nText: "When elegance meets perfection..." ${includeEmojis ? '✨' : ''}\n\n🎬 SCENE 2 - REVEAL (3-7s):\n[Slow-motion reveal]\nModel turns gracefully\nText: "${name}"\n\n🎬 SCENE 3 - DETAILS (7-12s):\n[Quick cuts showing:]\n- Fabric texture\n- Stitching details\n- Movement/flow\n- Different angles\n\n🎬 SCENE 4 - LIFESTYLE (12-18s):\n[Model in aspirational setting]\n- Walking confidently\n- Natural movement\n\n🎬 SCENE 5 - CTA (18-20s):\n[Product shot with branding]\nText: "${cta.en}" ${includeEmojis ? '🛍️' : ''}\n\n📝 CAPTION:\n${includeEmojis ? '✨ ' : ''}${name}\n${desc}\n${includeEmojis ? '👆 ' : ''}${cta.en}\n\n${includeHashtags ? '#fashion #luxury #style #ootd #designer #trending #viral #fyp #reels' : ''}`;
      contentAr += `📱 سكريبت ${platform.ar} - ${nameAr}\n\n⏱️ المدة: 15-30 ثانية\n\n🎬 المشهد 1 - الجذب (0-3 ثانية):\n[لقطة قريبة لتفاصيل القماش]\nالنص: "عندما تلتقي الأناقة بالكمال..." ${includeEmojis ? '✨' : ''}\n\n🎬 المشهد 2 - الكشف (3-7 ثانية):\n[كشف بالحركة البطيئة]\nالعارضة تدور برشاقة\nالنص: "${nameAr}"\n\n🎬 المشهد 3 - التفاصيل (7-12 ثانية):\n[لقطات سريعة تظهر:]\n- ملمس القماش\n- تفاصيل الخياطة\n- الحركة/التدفق\n- زوايا مختلفة\n\n🎬 المشهد 4 - أسلوب الحياة (12-18 ثانية):\n[العارضة في مكان ملهم]\n- تمشي بثقة\n- حركة طبيعية\n\n🎬 المشهد 5 - الدعوة للعمل (18-20 ثانية):\n[لقطة المنتج مع العلامة]\nالنص: "${cta.ar}" ${includeEmojis ? '🛍️' : ''}\n\n📝 الكابشن:\n${includeEmojis ? '✨ ' : ''}${nameAr}\n${descAr}\n${includeEmojis ? '👆 ' : ''}${cta.ar}\n\n${includeHashtags ? '#أزياء #فاشن #موضة #ستايل #تصميم #ترند #ريلز #لوك #اناقة' : ''}`;
    } else if (marketingPlatform === 'instagram-post') {
      contentEn += `📸 INSTAGRAM POST - ${name}\n\n${includeEmojis ? '✨ ' : ''}${name}\n\n${desc}\n\n${includeEmojis ? '💫 ' : ''}What makes it special:\n• Crafted from the finest materials\n• Attention to every detail\n• Timeless elegance meets modern design\n• Perfect for your most memorable moments\n\n${includeEmojis ? '🛍️ ' : ''}${cta.en}\n\n${includeHashtags ? '#fashion #style #luxury #designer #ootd #fashionblogger #instafashion' : ''}`;
      contentAr += `📸 بوست انستغرام - ${nameAr}\n\n${includeEmojis ? '✨ ' : ''}${nameAr}\n\n${descAr}\n\n${includeEmojis ? '💫 ' : ''}ما يميزها:\n• مصنوعة من أجود الخامات\n• اهتمام بكل تفصيلة\n• أناقة خالدة تلتقي بالتصميم العصري\n• مثالية للحظاتك المميزة\n\n${includeEmojis ? '🛍️ ' : ''}${cta.ar}\n\n${includeHashtags ? '#أزياء #ستايل #فخامة #مصمم #لوك_اليوم #فاشن #موضة' : ''}`;
    } else if (marketingPlatform === 'instagram-story') {
      contentEn += `📱 STORY SEQUENCE - ${name}\n\nSTORY 1 - TEASER:\n[Blurred/partial image]\nText: "Something special is here..." ${includeEmojis ? '👀' : ''}\nSticker: Countdown timer\n\nSTORY 2 - REVEAL:\n[Full product shot]\nText: "${name}" ${includeEmojis ? '✨' : ''}\nSticker: "NEW"\n\nSTORY 3 - DETAILS:\n[Close-up video of details]\nAdd Poll: "Which detail is your favorite?"\nOptions: "The fabric ✨" / "The design 💫"\n\nSTORY 4 - STYLING:\n[Product styled/on model]\nAdd Quiz: "Guess the occasion?"\n\nSTORY 5 - CTA:\n[Product with price/info]\nText: "${cta.en}" ${includeEmojis ? '🛍️' : ''}\nLink sticker: Direct to product`;
      contentAr += `📱 سلسلة ستوري - ${nameAr}\n\nستوري 1 - تشويق:\n[صورة ضبابية/جزئية]\nالنص: "شيء مميز وصل..." ${includeEmojis ? '👀' : ''}\nملصق: عداد تنازلي\n\nستوري 2 - الكشف:\n[لقطة كاملة للمنتج]\nالنص: "${nameAr}" ${includeEmojis ? '✨' : ''}\nملصق: "جديد"\n\nستوري 3 - التفاصيل:\n[فيديو قريب للتفاصيل]\nاستطلاع: "أي تفصيلة المفضلة؟"\nالخيارات: "القماش ✨" / "التصميم 💫"\n\nستوري 4 - التنسيق:\n[المنتج منسق/على عارضة]\nاختبار: "خمني المناسبة؟"\n\nستوري 5 - الدعوة للعمل:\n[المنتج مع السعر/المعلومات]\nالنص: "${cta.ar}" ${includeEmojis ? '🛍️' : ''}\nملصق الرابط: مباشر للمنتج`;
    } else {
      contentEn += `📝 ${platform.en} - ${name}\n\n${includeEmojis ? '✨ ' : ''}${name}\n${desc}\n\n${includeEmojis ? '🛍️ ' : ''}${cta.en}\n\n${includeHashtags ? '#fashion #style #luxury' : ''}`;
      contentAr += `📝 ${platform.ar} - ${nameAr}\n\n${includeEmojis ? '✨ ' : ''}${nameAr}\n${descAr}\n\n${includeEmojis ? '🛍️ ' : ''}${cta.ar}\n\n${includeHashtags ? '#أزياء #ستايل #فخامة' : ''}`;
    }
    setGeneratedPrompt(contentEn);
    setArabicContent(contentAr);
  };

  const generateStoryPrompt = () => {
    const tone = tones.find(t => t.id === storyTone);
    const desc = storyDesc || 'A luxurious fashion piece with exquisite details and premium craftsmanship';
    const descAr = storyDesc || 'قطعة أزياء فاخرة بتفاصيل راقية وحرفية متميزة';
    let storyEn = inputMode === 'image' && uploadedImage ? '[Based on uploaded product image]\n\n' : '';
    let storyAr = inputMode === 'image' && uploadedImage ? '[بناءً على صورة المنتج المرفقة]\n\n' : '';
    storyEn += `📖 MARKETING STORY\n\nTone: ${tone.en}\nProduct: ${desc}\n\n━━━━━━━━━━━━━━━━━━━━━━\n\n`;
    storyAr += `📖 قصة تسويقية\n\nالنبرة: ${tone.ar}\nالمنتج: ${descAr}\n\n━━━━━━━━━━━━━━━━━━━━━━\n\n`;
    
    const storiesEn = {
      luxury: {
        short: `In a world where ordinary is forgotten, we created the extraordinary. This isn't just fashion—it's a statement of who you are. Every stitch whispers luxury, every fold speaks elegance. For those who refuse to blend in.`,
        medium: `There are moments that define us. Moments when we walk into a room and time seems to pause. When all eyes turn, not because we demand attention, but because we command presence.\n\nThis piece was born from that vision—a vision of unapologetic elegance, of craftsmanship that honors tradition while embracing the bold spirit of modern femininity.\n\nEvery detail has been considered. Every stitch placed with intention. From the whisper of the fabric against your skin to the way it moves with your every step—this is fashion elevated to art.\n\nBecause you don't just wear luxury. You embody it.`,
        long: `THE ART OF PRESENCE\n\nIn the quiet moments before dawn breaks over the atelier, when the city still sleeps and dreams linger in the air, magic happens. Hands that have mastered their craft over decades begin their delicate dance with fabric, thread, and vision.\n\nThis is where your piece was born.\n\nNot in a factory. Not on an assembly line. But in a space where time moves differently—where hours disappear into the pursuit of perfection, where "good enough" is a phrase that doesn't exist.\n\nWe sourced this fabric from artisans who have guarded their secrets for generations. Feel it between your fingers—that subtle weight, that luminous sheen that catches light like captured moonbeams. This isn't just material. It's heritage woven into every thread.\n\nThe design emerged from countless sketches, each one bringing us closer to this moment—the moment when concept becomes reality, when imagination takes physical form. We rejected dozens of iterations. Because close to perfect isn't perfect.\n\nEvery seam has been reinforced by hand. Every edge finished with the precision of a master jeweler. Turn it inside out—we dare you. The interior is as flawless as the exterior, because true luxury doesn't hide behind façades.\n\nWhen you wear this piece, you're not just putting on a garment. You're stepping into a legacy. You're choosing to present yourself to the world as someone who understands that the finest things in life aren't about labels or trends—they're about an uncompromising commitment to excellence.\n\nThis is for the woman who walks into boardrooms and ballrooms with equal confidence. For the one who has worked for everything she has and chooses to celebrate that journey.\n\nNot just fashion. A declaration.\n\nWelcome to a new standard of elegance.`
      },
      friendly: {
        short: `Hey gorgeous! 👋 You know that feeling when you find THE piece? The one that makes you do a little spin in front of the mirror? Yeah, this is that piece. Made with love, designed for YOU. Let's make some heads turn together! 💕`,
        medium: `Can we talk for a sec? 💕\n\nYou know those days when your closet feels full but you have "nothing to wear"? We've ALL been there. That's exactly why we created this piece.\n\nIt's not trying to be everything to everyone. It's designed to be YOUR go-to—the piece you reach for when you want to feel put-together without trying too hard. Comfortable enough for all-day wear, stunning enough for that unexpected dinner invite.\n\nWe obsessed over every detail so you don't have to stress. The fit? Tested on real bodies, not just mannequins. The fabric? Feels like a dream, looks like a million bucks.\n\nThis is fashion that gets you. Finally. 🙌`,
        long: `LET'S GET REAL FOR A MINUTE 💕\n\nSo here's the thing—we started this brand because we were frustrated. Frustrated with fashion that promised comfort but delivered discomfort. With "luxury" that fell apart after three washes. With sizing that made no sense and return policies that felt like punishment.\n\nSound familiar?\n\nWe thought so.\n\nThat's why every single decision we make starts with one question: "Would WE want this?" Not what's trending. Not what's cheapest to produce. What would make us genuinely excited to open that package?\n\nThis piece? It took us 8 months to perfect. EIGHT. MONTHS. Our manufacturer probably thought we were crazy (honestly, fair). But we kept sending it back. The sleeve wasn't quite right. The hem needed adjusting. The color was 0.5% off from what we envisioned.\n\nBecause here's what we believe: you work hard for your money. Like, HARD. And when you choose to spend it with us, that means something. It means you trusted us with a little piece of your hard-earned paycheck, and we refuse—REFUSE—to let you down.\n\nSo when this arrives at your door, we want you to have that moment. You know the one. Where you try it on, look in the mirror, and just... smile. Not because it's fine. Not because it'll do. Because it's exactly what you hoped it would be.\n\nThe fabric moves with you, not against you. The cut flatters without squeezing. The style is current but not try-hard. It's the piece your future self will thank you for buying.\n\nWelcome to fashion that actually cares. We're so happy you're here. 💕`
      },
      inspiring: {
        short: `She didn't dress for others. She dressed for the woman she was becoming. Every morning, she chose pieces that reminded her of her power. This is one of those pieces. For every woman writing her own story. ✨`,
        medium: `Before she satisfies the world, she was herself.\n\nShe learned early that waiting for permission meant waiting forever. So she stopped asking. She started choosing—her path, her voice, her style.\n\nThis piece isn't about fitting in. It's about standing out on your own terms. It's for the woman who knows that true style isn't about following—it's about leading.\n\nSome will understand. Some won't. She dresses for the ones who do, and inspires the ones who will.\n\nYour moment isn't coming. It's here. Dress for it.`,
        long: `THE WOMAN WHO CHOSE HERSELF\n\nShe remembers the moment everything changed.\n\nIt wasn't dramatic—no lightning bolt, no sudden revelation. Just a quiet morning, standing in front of her closet, reaching for the same safe choices she always made. And then... she didn't.\n\nThat day, she chose differently. Not louder. Not more expensive. Just more HER.\n\nIt started with clothes but it didn't end there. That small act of choosing herself rippled outward. She spoke up in meetings. She asked for the promotion. She set boundaries she'd been afraid to set. She finally started that project she'd been "thinking about" for years.\n\nAll because one morning, she decided to stop dressing for disappearance and start dressing for presence.\n\nThis piece carries that energy.\n\nIt was designed for women at crossroads. For the one deciding whether to play it safe or bet on herself. For the one who's tired of blending into beige backgrounds. For the one ready to be seen—really seen—for exactly who she is.\n\nWear this on the day you ask for what you deserve. On the day you walk away from what no longer serves you. On the day you finally stop apologizing for taking up space.\n\nBecause here's what we know: clothes don't change your life. YOU change your life. But the right piece? It can remind you of who you're becoming. It can be armor when you need protection and wings when you're ready to soar.\n\nThis is for you.\n\nNow go show them what you're made of. ✨`
      },
      professional: {
        short: `Crafted with precision. Designed for excellence. This piece represents our commitment to quality that speaks for itself. For the professional who values substance over flash.`,
        medium: `In a market saturated with trends, we chose a different path: timeless quality.\n\nThis piece represents months of development, countless iterations, and an unwavering commitment to excellence. We partnered with artisans who share our vision—professionals who understand that true craftsmanship cannot be rushed.\n\nThe result speaks for itself. Superior materials, impeccable construction, and a design that transcends seasonal trends. This is an investment piece, built to serve you for years to come.\n\nFor the discerning professional who understands that quality is never an expense—it's an investment.`,
        long: `A NOTE ON CRAFTSMANSHIP\n\nIn an era of fast fashion and disposable trends, we made a deliberate choice to swim against the current.\n\nMATERIAL SELECTION\nOur sourcing process begins 18 months before a piece reaches you. We work exclusively with mills that meet our stringent quality standards—facilities that prioritize sustainable practices and fair labor conditions. Each fabric is tested for durability, colorfastness, and hand feel. We reject approximately 70% of samples before finding materials worthy of our collection.\n\nDESIGN PHILOSOPHY\nOur design team operates on a simple principle: create pieces you'll want to wear 10 years from now. This means avoiding trend-dependent elements while incorporating subtle contemporary touches. Every silhouette is refined over multiple seasons, tested across diverse body types, and adjusted until it achieves what we call "effortless elegance."\n\nCONSTRUCTION STANDARDS\nEach piece passes through 47 quality checkpoints. Seams are reinforced at stress points. Hems are weighted for optimal drape. Hardware is tested to withstand 10,000 uses. We maintain a defect tolerance of less than 0.3%—significantly below industry standards.\n\nTHE RESULT\nWhat you receive is not merely a garment. It is the culmination of expertise, intention, and an uncompromising commitment to excellence. A piece designed to become a cornerstone of your professional wardrobe.\n\nWe invite you to experience the difference that true quality makes.`
      }
    };
    
    const storiesAr = {
      luxury: {
        short: `في عالم يُنسى فيه العادي، صنعنا الاستثنائي. هذه ليست مجرد أزياء—إنها بيان عن هويتك. كل غرزة تهمس بالفخامة، كل طية تنطق بالأناقة. لمن يرفضون الذوبان في الحشود.`,
        medium: `هناك لحظات تحددنا. لحظات ندخل فيها غرفة ويبدو أن الزمن يتوقف. عندما تتجه كل الأنظار، ليس لأننا نطلب الاهتمام، بل لأننا نفرض الحضور.\n\nوُلدت هذه القطعة من تلك الرؤية—رؤية الأناقة بلا اعتذار، والحرفية التي تكرم التقاليد بينما تحتضن الروح الجريئة للأنوثة العصرية.\n\nكل تفصيلة تم التفكير فيها. كل غرزة وُضعت بقصد. من همس القماش على بشرتك إلى طريقة حركته مع كل خطوة تخطينها—هذه أزياء ارتقت إلى فن.\n\nلأنك لا ترتدين الفخامة فحسب. أنتِ تجسدينها.`,
        long: `فن الحضور\n\nفي اللحظات الهادئة قبل انبلاج الفجر فوق المشغل، عندما تكون المدينة نائمة والأحلام معلقة في الهواء، يحدث السحر. أيدٍ أتقنت حرفتها عبر عقود تبدأ رقصتها الرقيقة مع القماش والخيط والرؤية.\n\nهنا وُلدت قطعتك.\n\nليس في مصنع. ليس على خط تجميع. بل في مساحة يتحرك فيها الزمن بشكل مختلف—حيث تختفي الساعات في السعي نحو الكمال، حيث "جيد بما فيه الكفاية" عبارة غير موجودة.\n\nحصلنا على هذا القماش من حرفيين حرسوا أسرارهم لأجيال. تحسسيه بين أصابعك—ذلك الثقل الخفي، تلك اللمعة المضيئة التي تلتقط الضوء كأشعة قمر أسيرة. هذه ليست مجرد مادة. إنها إرث منسوج في كل خيط.\n\nانبثق التصميم من رسومات لا تُحصى، كل واحدة تقربنا من هذه اللحظة—اللحظة التي يصبح فيها المفهوم واقعاً، حين يتخذ الخيال شكلاً ملموساً. رفضنا عشرات النسخ. لأن القريب من الكمال ليس كمالاً.\n\nكل درزة عُززت يدوياً. كل حافة أُنهيت بدقة صائغ مجوهرات ماهر.\n\nعندما ترتدين هذه القطعة، أنتِ لا تلبسين مجرد ثوب. أنتِ تدخلين في إرث. أنتِ تختارين تقديم نفسك للعالم كشخص يفهم أن أرقى الأشياء في الحياة ليست عن العلامات التجارية أو الصيحات—إنها عن التزام لا يتزعزع بالتميز.\n\nهذا للمرأة التي تدخل غرف الاجتماعات وقاعات الحفلات بثقة متساوية.\n\nليست مجرد أزياء. إنها إعلان.\n\nمرحباً بكِ في معيار جديد للأناقة.`
      },
      friendly: {
        short: `هاي يا حلوة! 👋 تعرفين ذلك الشعور لما تلاقين القطعة المثالية؟ تلك التي تخليكِ تدورين قدام المرآة؟ أيوا، هذي هي تلك القطعة. مصنوعة بحب، مصممة لكِ. خلينا نلفت الأنظار سوا! 💕`,
        medium: `ممكن نحكي لحظة؟ 💕\n\nتعرفين تلك الأيام لما تحسين خزانتك مليانة بس "ما في شي تلبسينه"؟ كلنا مرينا بهذا. لهذا بالضبط صنعنا هذه القطعة.\n\nما تحاول تكون كل شي لكل الناس. مصممة لتكون قطعتك المفضلة—اللي تمدين إيدك لها لما تبين تحسين بأناقة بدون مجهود كبير. مريحة بما يكفي لليوم كله، مذهلة بما يكفي لدعوة عشاء مفاجئة.\n\nاهتمينا بكل تفصيلة عشان ما تقلقين. القصة؟ جربناها على أجسام حقيقية. القماش؟ إحساسه حلم، شكله مليون.\n\nهذي أزياء تفهمك. أخيراً. 🙌`,
        long: `خلينا نكون صريحين لدقيقة 💕\n\nالموضوع هو—بدأنا هذا البراند لأننا كنا محبطين. محبطين من أزياء وعدت بالراحة وقدمت الانزعاج. من "فخامة" تفككت بعد ثلاث غسلات. من مقاسات ما كان لها معنى.\n\nمألوف؟\n\nتوقعنا ذلك.\n\nلهذا كل قرار ناخذه يبدأ بسؤال واحد: "هل نحن نبي هذا؟" مش شو الترند. مش شو الأرخص للإنتاج. شو اللي يخلينا فعلاً متحمسين نفتح تلك الشحنة؟\n\nهذه القطعة؟ أخذت منا 8 شهور لنتقنها. ثمانية. شهور.\n\nلأن هذا اللي نؤمن فيه: أنتِ تشتغلين بجد على فلوسك. ولما تختارين تصرفينها معنا، هذا يعني شي. يعني وثقتِ فينا بجزء صغير من راتبك اللي تعبتِ عليه، ونحن نرفض—نرفض—نخذلك.\n\nفلما توصل لبابك، نبيك تعيشين تلك اللحظة. لما تجربينها، تطالعين بالمرآة، وبس... تبتسمين. لأنها بالضبط اللي تمنيتيها.\n\nالقماش يتحرك معك، مش ضدك. القصة تناسب بدون ما تضغط. الستايل عصري بس مش متكلف.\n\nمرحباً بك في أزياء تهتم فعلاً. مبسوطين إنك هنا. 💕`
      },
      inspiring: {
        short: `لم تكن تلبس للآخرين. كانت تلبس للمرأة التي تصبحها. كل صباح، اختارت قطعاً تذكرها بقوتها. هذه واحدة من تلك القطع. لكل امرأة تكتب قصتها الخاصة. ✨`,
        medium: `قبل أن ترضي العالم، كانت نفسها.\n\nتعلمت باكراً أن انتظار الإذن يعني الانتظار للأبد. فتوقفت عن السؤال. بدأت تختار—طريقها، صوتها، أسلوبها.\n\nهذه القطعة ليست عن الاندماج. إنها عن التميز بشروطك الخاصة. إنها للمرأة التي تعرف أن الستايل الحقيقي ليس عن الاتباع—إنه عن القيادة.\n\nالبعض سيفهم. البعض لن يفهم. هي تلبس لمن يفهمون، وتلهم من سيفهمون.\n\nلحظتك ليست قادمة. إنها هنا. البسي لها.`,
        long: `المرأة التي اختارت نفسها\n\nتتذكر اللحظة التي تغير فيها كل شيء.\n\nلم تكن درامية—لا صاعقة برق، لا إلهام مفاجئ. فقط صباح هادئ، واقفة أمام خزانتها، تمد يدها للخيارات الآمنة ذاتها التي طالما اختارتها. وبعدها... لم تفعل.\n\nذلك اليوم، اختارت بشكل مختلف. ليس أعلى صوتاً. ليس أغلى ثمناً. فقط أكثر انتماءً لها.\n\nبدأ بالملابس لكنه لم ينتهِ هناك. ذلك الفعل الصغير من اختيار نفسها امتد للخارج. تكلمت في الاجتماعات. طلبت الترقية. وضعت حدوداً كانت تخاف أن تضعها. أخيراً بدأت ذلك المشروع الذي كانت "تفكر فيه" لسنوات.\n\nكل ذلك لأنها صباحاً واحداً، قررت أن تتوقف عن اللبس للاختفاء وتبدأ اللبس للحضور.\n\nهذه القطعة تحمل تلك الطاقة.\n\nصُممت للنساء عند مفترقات الطرق. للتي تقرر إن كانت ستلعبها آمنة أم تراهن على نفسها. للتي مستعدة أن تُرى—تُرى فعلاً—لمن هي بالضبط.\n\nالبسيها يوم تطلبين ما تستحقين. يوم تمشين بعيداً عما لم يعد يخدمك. يوم تتوقفين أخيراً عن الاعتذار لأنك تأخذين مساحة.\n\nهذه لكِ.\n\nالآن اذهبي أريهم مما أنتِ مصنوعة. ✨`
      },
      professional: {
        short: `مصنوعة بدقة. مصممة للتميز. هذه القطعة تمثل التزامنا بالجودة التي تتحدث عن نفسها. للمحترفة التي تقدر الجوهر على البريق.`,
        medium: `في سوق مشبع بالصيحات، اخترنا طريقاً مختلفاً: الجودة الخالدة.\n\nهذه القطعة تمثل شهوراً من التطوير، تكرارات لا تُحصى، والتزاماً لا يتزعزع بالتميز. شاركنا حرفيين يشاركوننا رؤيتنا—محترفين يفهمون أن الحرفية الحقيقية لا يمكن استعجالها.\n\nالنتيجة تتحدث عن نفسها. مواد متفوقة، بناء لا تشوبه شائبة، وتصميم يتجاوز صيحات المواسم. هذه قطعة استثمارية.\n\nللمحترفة الذواقة التي تفهم أن الجودة ليست أبداً مصروفاً—إنها استثمار.`,
        long: `ملاحظة عن الحرفية\n\nفي عصر الموضة السريعة والصيحات القابلة للتخلص، اتخذنا خياراً متعمداً للسباحة عكس التيار.\n\nاختيار المواد\nتبدأ عملية التوريد لدينا قبل 18 شهراً من وصول القطعة إليك. نعمل حصرياً مع مصانع تلبي معايير الجودة الصارمة لدينا. كل قماش يُختبر للمتانة وثبات اللون والملمس. نرفض حوالي 70% من العينات قبل إيجاد مواد جديرة بمجموعتنا.\n\nفلسفة التصميم\nيعمل فريق التصميم لدينا على مبدأ بسيط: صنع قطع ستريدين ارتداءها بعد 10 سنوات من الآن. هذا يعني تجنب العناصر المعتمدة على الصيحات مع دمج لمسات عصرية خفية.\n\nمعايير البناء\nكل قطعة تمر عبر 47 نقطة فحص جودة. الدرزات مُعززة في نقاط الإجهاد. الحواشي موزونة للانسدال الأمثل.\n\nالنتيجة\nما تستلمينه ليس مجرد ثوب. إنه تتويج للخبرة والقصد والالتزام الصارم بالتميز. قطعة مصممة لتصبح حجر أساس في خزانتك المهنية.\n\nندعوك لتجربة الفرق الذي تصنعه الجودة الحقيقية.`
      }
    };
    
    const toneKey = storyTone === 'playful' ? 'friendly' : storyTone === 'urgent' ? 'professional' : storyTone;
    storyEn += storiesEn[toneKey]?.[storyLength] || storiesEn.luxury.medium;
    storyAr += storiesAr[toneKey]?.[storyLength] || storiesAr.luxury.medium;
    setGeneratedPrompt(storyEn);
    setArabicContent(storyAr);
  };

  const handleGenerate = () => { setShowArabic(false); if (activeTab === 'design') generateDesignPrompt(); else if (activeTab === 'video') generateVideoPrompt(); else if (activeTab === 'marketing') generateMarketingPrompt(); else if (activeTab === 'story') generateStoryPrompt(); };
